name: firebase_functions_interop_test
description: Test Firebase Functions Interop
version: 0.0.0
#homepage: https://www.example.com
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  firebase_functions_interop:
    path: ../

dev_dependencies:
  build_runner: ^2.0.3
  build_node_compilers:
    git: # temporary until NNBD approved for main package
      url: https://github.com/SupposedlySam/node-interop.git
      path: build_node_compilers
