name: firebase_functions_interop
description: Firebase Cloud Functions SDK for Dart written as a JS interop wrapper for official Node.js SDK.
version: 2.0.0
homepage: https://www.github.com/pulyaevskiy/firebase-functions-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  js: ^0.6.3
  meta: ^1.3.0
  node_interop: ^2.0.1
  node_io: ^2.0.0
  node_http:
    git: # temporary until NNBD approved for main package
      url: https://github.com/SupposedlySam/node-interop.git
      path: node_http
  firebase_admin_interop: 
    git: git@github.com:SupposedlySam/firebase-admin-interop.git

dev_dependencies:
  test: ^1.17.4
